module.exports = {
    users: [
        {
            user_id: 1,
            user_name: 'usample',
            user_email: 'user_sample@doggo.com',
            is_admin: true,
            is_poster: false,
        },
        {
            user_id: 2,
            user_name: 'fifi',
            user_email: 'fifi@ismycat.com',
            is_admin: false,
            is_poster: false,
        },
        {
            user_id: 3,
            user_name: 'mochi',
            user_email: 'mochi@issomeothercat.com',
            is_admin: false,
            is_poster: false,
        },
        {
            user_id: 4,
            user_name: 'archie',
            user_email: 'ar_cat@hires.com',
            is_admin: false,
            is_poster: true,
        },
        {
            user_id: 5,
            user_name: 'lulu',
            user_email: 'totallylegit@pets.com',
            is_admin: false,
            is_poster: false,
        },
    ],
    profiles: [
        { profile_id: 1, user_id: 1 },
        { profile_id: 2, user_id: 2 },
        { profile_id: 3, user_id: 3 },
        { profile_id: 4, user_id: 4 },
        { profile_id: 5, user_id: 5 },
        { profile_id: 6, user_id: 6 },
        { profile_id: 7, user_id: 7 },
    ],
    response_keys: [
        {
            response_key_id: 1,
            response_key_category: 'grit',
            response_key_prompt: 'what is your name',
            response_key_description: null,
        },
        {
            response_key_id: 2,
            response_key_category: 'openness',
            response_key_prompt: 'what is your favorite color',
            response_key_description: null,
        },
        {
            response_key_id: 3,
            response_key_category: 'grit',
            response_key_prompt: 'what is your quest',
            response_key_description: null,
        },
        {
            response_key_id: 4,
            response_key_category: 'empathy',
            response_key_prompt:
                'what is the average flight speed of an unladen swallow',
            response_key_description: null,
        },
    ],
    responses: [
        { response_id: 1, profile_id: 2, response_key_id: 2, val: '80' },
        { response_id: 2, profile_id: 2, response_key_id: 1, val: '70' },
        { response_id: 3, profile_id: 2, response_key_id: 1, val: '50' },
        {
            response_id: 4,
            profile_id: 2,
            response_key_id: 3,
            val: 'I am actually a very experienced cat.',
        },
        {
            response_id: 5,
            profile_id: 3,
            response_key_id: 3,
            val: 'I am not a person but I need a job',
        },
        {
            response_id: 6,
            profile_id: 4,
            response_key_id: 3,
            val: 'Just a job that needs grit',
        },
        { response_id: 7, profile_id: 4, response_key_id: 2, val: '30' },
        { response_id: 8, profile_id: 4, response_key_id: 1, val: '100' },
        {
            response_id: 9,
            profile_id: 5,
            response_key_id: 3,
            val: 'This job posting is awful',
        },
    ],
    memberships: [
        {
            membership_id: 1,
            user_id: 1,
            grouping_id: 1,
            membership_type: '_admin',
            can_edit: true,
            is_active: true,
        },
        {
            membership_id: 2,
            user_id: 1,
            grouping_id: 2,
            membership_type: 'recruiter',
            can_edit: true,
            is_active: true,
        },
        {
            membership_id: 3,
            user_id: 1,
            grouping_id: 3,
            membership_type: 'participant',
            can_edit: false,
            is_active: true,
        },
        {
            membership_id: 4,
            user_id: 2,
            grouping_id: 3,
            membership_type: 'participant',
            can_edit: false,
            is_active: false,
        },
        {
            membership_id: 5,
            user_id: 3,
            grouping_id: 3,
            membership_type: 'participant',
            can_edit: false,
            is_active: false,
        },
        {
            membership_id: 6,
            user_id: 4,
            grouping_id: 4,
            membership_type: 'participant',
            can_edit: false,
            is_active: true,
        },
        {
            membership_id: 7,
            user_id: 2,
            grouping_id: 4,
            membership_type: 'participant',
            can_edit: false,
            is_active: false,
        },
        {
            membership_id: 8,
            user_id: 3,
            grouping_id: 5,
            membership_type: 'participant',
            can_edit: false,
            is_active: true,
        },
        {
            membership_id: 9,
            user_id: 1,
            grouping_id: 5,
            membership_type: 'participant',
            can_edit: false,
            is_active: true,
        },
    ],
    groupings: [
        {
            grouping_id: 1,
            grouping_name: '00000000_siimee_',
            grouping_type: 'company',
        },
        {
            grouping_id: 2,
            grouping_name: '01010101_testco_',
            grouping_type: 'company',
        },
        {
            grouping_id: 3,
            grouping_name: '11111111_usample_fifi',
            grouping_type: 'match',
        },
        {
            grouping_id: 4,
            grouping_name: '12121212_archie_fifi',
            grouping_type: 'match',
        },
        {
            grouping_id: 5,
            grouping_name: '32323232_mochi_usample',
            grouping_type: 'match',
        },
    ],
    messages: [
        { message_id: 1, user_id: 1, grouping_id: 3, message: 'hello' },
        { message_id: 2, user_id: 2, grouping_id: 3, message: 'hi' },
        { message_id: 3, user_id: 1, grouping_id: 3, message: 'how are you?' },
        {
            message_id: 4,
            user_id: 2,
            grouping_id: 3,
            message: 'doing well, and you?',
        },
        { message_id: 5, user_id: 1, grouping_id: 3, message: 'doing great' },
        { message_id: 6, user_id: 4, grouping_id: 4, message: 'hey' },
        { message_id: 7, user_id: 5, grouping_id: 4, message: 'just hey?' },
        { message_id: 8, user_id: 1, grouping_id: 5, message: 'hello!' },
        { message_id: 9, user_id: 3, grouping_id: 5, message: 'meow' },
    ],

    // Stores POTENTIAL matches

    matchque: [
        { match_id: 1, profile_id: 1, profile_id_2: 3, deleted: 0 },
        { match_id: 2, profile_id: 2, profile_id_2: 5, deleted: 0 },
        { match_id: 3, profile_id: 2, profile_id_2: 3, deleted: 0 },
        { match_id: 4, profile_id: 4, profile_id_2: 3, deleted: 0 },
        { match_id: 5, profile_id: 3, profile_id_2: 2, deleted: 0 },
        { match_id: 6, profile_id: 1, profile_id_2: 4, deleted: 0 },
        { match_id: 7, profile_id: 3, profile_id_2: 7, deleted: 0 },
        { match_id: 8, profile_id: 6, profile_id_2: 15, deleted: 0 },
        { match_id: 9, profile_id: 4, profile_id_2: 23, deleted: 0 },
        { match_id: 10, profile_id: 2, profile_id_2: 44, deleted: 0 }, // to test for collission
        { match_id: 11, profile_id: 2, profile_id_2: 44, deleted: 0 },
        { match_id: 12, profile_id: 3, profile_id_2: 9, deleted: 0 },
        { match_id: 13, profile_id: 5, profile_id_2: 5, deleted: 0 },
        { match_id: 14, profile_id: 6, profile_id_2: 3, deleted: 0 },
        { match_id: 15, profile_id: 5, profile_id_2: 2, deleted: 0 },
        { match_id: 16, profile_id: 2, profile_id_2: 7, deleted: 0 },
        { match_id: 17, profile_id: 7, profile_id_2: 8, deleted: 0 },
    ],
}
